### ISSUE TITLE
add a bn ban/appeal system

### ISSUE THREAD

**Issue by Hiviexd** [pishifat/qat#171]
a system like this is long overdue, making an issue for tracking purposes. system would be kinda similar to evals in workflow

## bans
- bans can only be applied on former members, so the nat would have to kick a bn, then ban them
- bans ban a user from all mode bngs, cuz bn bans are practically all behavior related
- create a /bans page, should contain a "create a ban" button, "pending bans" section, "active bans" section, an an "inactive bans" section that works just like the closed reports section
- an nat would generate a ban card in a "create a ban" page, specifies cooldown til they can appeal (can be a date or indefinite) and reason, then card would be put in a "waiting on confirmation" state in the "pending bans" section
- 3 (number kinda arbitrary, could be more?) nats (regardless of mode, doesn't have to be assigned) would approve said ban by clicking a button on the card and possibly writing a comment themselves
- after 3 approvals, card would be marked as "active" and be put in the active bans section

a ban card should include:
- user
- ban reason
- ban cooldown (editable)
- ban creator and ban approvers
- list of related appeals
- button to manually mark ban as inactive (or active for inactive bans)

also, on the small ban card, there should be an indication whether a ban is currently appealable or not, based on the cooldown date

## appeals
- create an /appeals page, should contain a "active appeals" section, and an "archived appeals" section that works just like the closed reports section
- when a banned user goes to /bnapps, instead of the app form they'll get a red ban alert, the date where they're allowed to appeal, and an appeal button in case they can actually appeal
- pressing the button would open up a form where the user can write their appeal and send it
- when an appeal is sent, an appeal card would pop up in the active appeals section, and workflow would be very similar to reports, where it displays the message, we can write our responses, choose consensus, and update ban cooldown so they can only re-appeal after new date.
- outcome of appeal would be delivered thru natbot
- if an appeal is granted, it'd mark the ban card and appeal as inactive, and allow user to re-apply
- if an appeal is denied, it'd mark the appeal card as inactive, keep the ban card as active, and update cooldown

**Comment by pishifat** [comment]
after talking in dms, we chose to go with
bans = option on user profile
appeal = email support
