### ISSUE TITLE
Able to type in other BN's request information if you leave the text editor open on your own profile

### ISSUE THREAD

**Issue by tilda** [pishifat/qat#264]
Best described in the following gif:

![](https://u.til.pm/2024/06/Bleak/firefox_FyysuvvgUE.gif)

Not sure if this is actually considered an issue and I didn't attempt *actually* updating them but yea

**Comment by pishifat** [comment]
try updating im curious if it works

@Hiviexd set this up, so maybe he knows a quick fix

**Comment by tilda** [comment]
unfortunately it seems the authorization actually works, day ruined
