### ISSUE TITLE
Navbar moves when hovering over item

### ISSUE THREAD

**Issue by Darius-Wattimena** [pishifat/qat#27]
Currently when you hover over a navbar item everything moves because when the hover or active state is applied to the `a` the `font-weight` is set to `bold`. This ends up increasing the size of the navbar item and move everything around it.

This could be fixed by simply unsetting the `font-weight` and instead fake the effect by using a `text-shadow: 0 0 0.1px #fff` if you want a quick and dirty fix.

**Comment by pishifat** [comment]
yes
